#   FOR  ARGPARSER
SOCK5_SERVER_MODE_LOCAL = "local"
SOCK5_SERVER_MODE_RELAY = "relay"

#   FOR SOCKS5 PARSER STAGE
SOCK5_PARSER_STAGE_INIT = 0
SOCK5_PARSER_STAGE_HOST = 1
SOCK5_PARSER_STAGE_DATA = 2

#   FOR RELAY STAGE
RELAY_SERVER_STAGE_CONNED = 0
RELAY_SERVER_STAGE_CONNING = 1